format = """
$directory\
$fossil_branch\
$git_branch\
$git_commit\
$git_status\
$fill\
$nodejs\
$cmd_duration $jobs\
$line_break\
$username\
[@](bold #CDCDCD)\
$hostname\
$character\
"""

[username]
show_always = true
disabled = false
format = "[$user](bold #34495E)"

[hostname]
trim_at = "."
ssh_only = false
format = "[$hostname ](bold #34495E)"

[nodejs]
symbol= "[NODE.JS:](#52BE80)"
format = "[$symbol([$version](#73C6B6))](bold)"

[character]
success_symbol = "[â¯](#138D75)"
error_symbol = "[â¯](#E74C3C)"
vicmd_symbol = "[â®](#17202A)"

[fill]
symbol = " "

[directory]
style = "bold #5D6D7E"
read_only = "ğŸ”’"
truncation_length = 4
truncate_to_repo = false

[git_branch]
symbol = "[âˆ™](red)"
style = "#D35400"
format = '[$symbol$branch(:$remote_branch)]($style)'


[git_commit]
commit_hash_length = 7
tag_symbol = ' ğŸ· '
disabled = false
style = 'bold green'
format = '[\($hash$tag\)]($style) '

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
modified = "[+${count}](bold green)"
untracked = "[+${count}](bold green)"
staged = "+${count}"
format = '([\[ğŸ“$modified | ğŸ¤·$untracked\]]($style))'
style = 'bold black'
disabled = false


[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[jobs]
symbol = "â±ï¸"
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"
